### ISSUE TITLE
Issue with RDP/RDSH

### ISSUE THREAD

**Issue by avassdal** [tomek-o/tSIP#11]
Hello

I´m having issues getting tSIP to work trough RDP/RDSH. 

If i don´t specify any device in Audio I/O i get audio ringing output, but this error when i answer:

Handling commnand line
answering call from sip:anonymous@anonymous.invalid with 200
Set audio decoder: PCMA 8000Hz 1ch
Set audio encoder: PCMA 8000Hz 1ch
waveInOpen: failed 0
start_source failed: Invalid argument (code 19)
sip:anonymous@anonymous.invalid: session closed: End of call (CANCEL received)

If i do specify All Audio I/O as Remote Audio with PortAudio there is still ringing and this i the output:

write stream latency = 100 ms
answering call from sip:anonymous@anonymous.invalid with 200
Set audio decoder: PCMA 8000Hz 1ch
write stream latency = 100 ms
Set audio encoder: PCMA 8000Hz 1ch
read: Pa_OpenStream: Unanticipated host error
start_source failed: Invalid argument (code 19)
sip:anonymous@anonymous.invalid: session closed: End of call (CANCEL received)

Any ideas where to start troubleshooting this?

**Comment by tomek-o** [comment]
Strangely I've received e-mail today with exactly the same error, but it wasn't from you, was it?
Apparently - as author found - in this case it was Windows 10 blocking access to audio device, Windows Settings -> Privacy -> Microphone AND Camera, like here:
https://support.discordapp.com/hc/en-us/articles/360004159932--Windows-10-Allowing-Access-for-Microphone-Camera
I remember being surprised by this after one Win10 update maybe year ago, I'd suggest checking it first.
