### ISSUE TITLE
Video Support

### ISSUE THREAD

**Issue by p5panam** [tomek-o/tSIP#14]
It will be great if you add video support on the VOIP, maybe using VP9 so we could do videocalls.

Also, it is very important if you could add ZRTP support on it.

**Comment by tomek-o** [comment]
I haven't seen much demand for video for years, but lately I've found some potential uses for it.

While it is only shortly tested and most likely has lots of issues, https://github.com/tomek-o/tSIP-video supports video (in default configuration only MP4V-ES) and in my test ZRTP seems to work also.

Note: ZRTP requires assigning few buttons for its purposes (there is no "default" GUI part), like in https://tomeko.net/software/SIPclient/howto/zrtp.php.
