### ISSUE TITLE
Handle multiple calls

### ISSUE THREAD

**Issue by victorkl400** [tomek-o/tSIP#15]
Is possible to receive more than one call simultaneously? I tried but seems like get busy state

**Comment by tomek-o** [comment]
It is limited to single call. I've tried multiple calls once on slightly modified version, but it was using other kind of GUI.

**Comment by tomek-o** [comment]
Update: support for multiple calls along with conferencing and attended transfer was recently added to pre-release: https://tomeko.net/software/SIPclient/howto/multiple_calls.php.
