### ISSUE TITLE
ho to compile the project on 2020

### ISSUE THREAD

**Issue by emilius3m** [tomek-o/tSIP#16]
I have serious problems finding and installing BDS2006.
I've already read https://github.com/tomek-o/tSIP/issues/13, but I can't get a working compiler.

**Comment by tomek-o** [comment]
For me Turbo C++ Explorer works on Windows 7 32/64-bit (minor startup issue solved by run_bds.bat/run_bds_x64.bat) and Windows 10 (no problems), but I don't think free license can be obtained these days.

I do also have (almost?) newest C++Builder 10.3.2 Rio Community Edition on other PC, but it fails to import TC++/BDS2006 projects directly, so projects probably would need to be recreated. GUI code would need some fixing too (transition to Unicode and few years of VCL evolution). Not difficult, but definitively time consuming.
