### ISSUE TITLE
Change User-Agent

### ISSUE THREAD

**Issue by aeri** [tomek-o/tSIP#17]
Some ISPs do not allow registration to be set if it does not match the User-Agent of their authorized devices, in order to avoid external settings.

Is it possible to change this User-Agent in tSIP?

Thank you.

**Comment by aeri** [comment]
Solved, found in tSIP.json configuration file.

```json
      "customUserAgent" : true,
      "userAgent" : "",
```

**Comment by tomek-o** [comment]
It is also visible in "Settings"/"Branding, bitmaps".

**Comment by aeri** [comment]
It's true, I didn't place it there and I didn't find it.
Thanks.
