### ISSUE TITLE
Conference calls and call waitting please.

### ISSUE THREAD

**Issue by carloselectro** [tomek-o/tSIP#18]
Hi,

It would be great to be able to make conference calls.
Call waitting is another option that I  am looking for, so I can take an incoming call if I'm already talking to someone.

Keep up the good work.

**Comment by Northernn** [comment]
If you use it on a sip pbx, then that should be able to handle both of these things, rather than the client software.

**Comment by InterLinked1** [comment]
Yes, you can use the FLASH button to do this. That makes this far and away more capable than most other softphones already. Let the switch do the job it's there for.

**Comment by tomek-o** [comment]
There is some very early work on this in https://github.com/tomek-o/tSIP/tree/feature-multiple-calls branch.
Description: https://tomeko.net/software/SIPclient/howto/multiple_calls.php.
