### ISSUE TITLE
Custom ring cadences do not loop properly

### ISSUE THREAD

**Issue by InterLinked1** [tomek-o/tSIP#24]
I noticed that when custom ring cadences are provided for distinctive ringing, they do not loop properly.

What I have done is record samples of a standard 500 or 2500 set ringing with each of the different cadences. However, there seems to be some delay between loops, which means the cadence is interrupt with silence between repetitions of the file. It doesn't make sense to record a super long WAV file just to get around this, nor to anticipate the silence in the recording.

I propose that if this is unintentional, this behavior should be corrected so the timing works, or if it is intentional, an option should be provided to loop immediately.

Thank you!

**Comment by tomek-o** [comment]
There is new setting on the "Ring" page now: "Loop ring without silence", added in https://github.com/tomek-o/tSIP/commit/d00fea9f78f33ce69e6a023b9a9ecd26a591b3f0.
Executable is as usual at http://tomeko.net/tmp/tSIP.exe.
