### ISSUE TITLE
Pass argument to lua-Script

### ISSUE THREAD

**Issue by simnzz** [tomek-o/tSIP#30]
Hi, thanks for your great tool! I'm new to lua - and your solution :-)

I've managed it to launch (by powershell) tsip with a lua script to call a number and play a text-to-speech generated wave-file in a loop. Is it possible to pass an argument to the lua script (with the number to call and maybe other parameters?). I'd like to check for a dtmf-callback to send an email to a passed by argument defined email-address.

**Comment by tomek-o** [comment]
Passing between scripts ("global" variable mechanism and queues) or from other application?
For passing from other applications some options might be:

- creating whole script file in other application, saving it to \scripts and calling tSIP: tSIP.exe /tSIP=SCRIPT_FILE=test2.lua
- like above but creating partial script containing only something that changes; this file might then include some other, bigger script
- very short scripts (escaping seems to be a big problem) might be passed directly from command line: tsip.exe /tsip=SCRIPT=ShowMessage('test'); example: https://tomeko.net/software/SIPclient/howto/command_script_and_call_queue.php
- for longer scripts escaping with base64 might be necessary: tsip.exe /tsip=SCRIPT_B64=XXXXXXXXXXXXXXXXXXXXXXXXXXX
- creating some file that contains parameters and reading it inside script
- passing parameters by clipboard (probably would work best with script assigned to button with some hotkey assigned)

In Settings/Integration "Accept scripts from command line" must be checked - as same mechanism might be used for passing parameters from web browser I felt like it might be too powerful and shouldn't be enabled by default.
Note that in default configuration parameters are passed to previous instance if this instance was found, so application may run (being registered and subscribing to events continuously) for a long time while accepting new parameters.

**Comment by simnzz** [comment]
You're great, thank you! I've managed it know by chaging the variables inside the lua script by powershell.

Regards
Simon
