### ISSUE TITLE
Buttons not showing text

### ISSUE THREAD

**Issue by Northernn** [tomek-o/tSIP#33]
When you program a button in the bottom 2 rows using BLF and any text in the caption, no text shows at all, if you change it to something else like speeddial it shows fine, it only seems to affect the bottom 2 rows of buttons.

**Comment by tomek-o** [comment]
Second line from BLF button is mostly for remote identity only upon receiving notification (if subscribing to non-existing resource it stays as defined by the user) - it shows call direction and caller/callee number or name. I might be missing something but testing now I see that user label is left intact if remote identity is not sent by PABX.
Presence works in a similar way - second line is mostly for user status text.

**Comment by Northernn** [comment]
I got hold of a second computer and the issue does not occur, so it is computer specific not application issue.

**Comment by tomek-o** [comment]
It would be hard to believe that this is computer specific, maybe it would resurface later.

**Comment by Northernn** [comment]
I got it again on a different computer, it only affected button #54 and #55

I just edit the button
Change the type to BLF
Type in Caption Hold 4
Type in Number 74
Hit Apply

It only shows the green phone icon and not the text "Hold 4"

It should be showing Hold 3 and Hold 4 in the screenshot attached,


![buttons](https://user-images.githubusercontent.com/67755436/171273346-cec06375-14e1-4667-8d1e-c4dbcd57a35c.png)

**Comment by tomek-o** [comment]
This looks really weird. I see also something resembling visual glitch slightly above these buttons. I'm assuming this is Windows 11, would setting some compatibility mode affect this?
Would setting button type to 2 caption lines or changing font affect this?

**Comment by Northernn** [comment]
The glitch on the button above was just me blanking out a button, that button is fine.
Yes it is windows 11
I tried windows 8 compatibility but it had no effect

https://user-images.githubusercontent.com/67755436/171287147-e83c39cf-bbdf-4e3a-8eef-4b9b880ba950.mp4

**Comment by Northernn** [comment]
quality isn't great but the 2nd line seems to display, but not the first line

**Comment by Northernn** [comment]
The glitch on the button above was just me blanking out a button, that button is fine.
Yes it is windows 11
I tried windows 8 compatibility but it had no effect

The 2nd line seems to work fine with a 2nd line caption, the 1st one is still blanked out
![buttons 2](https://user-images.githubusercontent.com/67755436/171288132-e0dd568c-74e4-4219-9ebc-801917f31e2a.png)
.

**Comment by tomek-o** [comment]
Could you mail me your tSIP_buttons.json? Maybe there is something I'm missing. There shouldn't be anything specific about these two buttons and even their location is just part of default configuration, so "rows" and "columns" is just the default setup.

**Comment by tomek-o** [comment]
Is there any script or plugin using SetButtonCaption() or UpdateButtons() functions maybe?

**Comment by Northernn** [comment]
The only plugin is the HID one and the scripts I cannot see either of those in any scripts.

It only seemes to be specific buttons though, I tested a few and it only happens on very specific buttons,, such as #55 and #54
Other buttons seem to do it fine.

**Comment by tomek-o** [comment]
Unfortunately I wasn't able to reproduce this. Maybe later I'll try to prepare some portable minimal Windows FreeSWITCH version that could help - working as common, easy to share PABX for testing. Maybe attached debug version with CodeGuard enabled would point to some memory corruption?
[tSIP_debug.zip](https://github.com/tomek-o/tSIP/files/8874068/tSIP_debug.zip)

**Comment by Northernn** [comment]
Finally got round to this, the debug version doesn't run

![dll](https://user-images.githubusercontent.com/67755436/181215124-690fe41a-004c-444f-b194-200a8173b91d.png)

**Comment by tomek-o** [comment]
It looks like I've included wrong dll set in this zip, sorry. Here are correct ones:
[cg32_borlndmm.zip](https://github.com/tomek-o/tSIP/files/9200890/cg32_borlndmm.zip)

**Comment by Northernn** [comment]
I finally got round to deugging it and I found a line in a script that seems to be the cause of the problem
SetButtonCaption2(btn2Id, line4)
Removed this and the line no longer blanks.
