### ISSUE TITLE
History ListColumnWidths expands after every program start

### ISSUE THREAD

**Issue by itskaefer** [tomek-o/tSIP#37]
After every program start or exit tSIP safes a bigger value for every column.
For example I manually set History -> ListColumnWidths to [ 100, 200 ] in the tSIP.json config file.
I start tSIP and the window shows the columns Timestamp and Name/number as expected under History

After exiting tSIP without changing anything at all I open the tSIP.json again and the values are now [ 125, 250 ] for ListColumnWidths.

After repeating the same procedure the values are [ 156, 312 ], then [ 243, 487 ] and so on.
Until I cannot see the name column in the History window.
And there is no way to rearrange the column width in tSIP let's say with the pointer for a quick correction.

It looks like it has something to do with the GUI scaling.
I have GUI scaling set to 125%.

**Comment by tomek-o** [comment]
Thanks for reporting and diagnosing.

I've fixed it in https://tomeko.net/tmp/tSIP.exe.

Same compilation also fixes positions/sizes of dialpad elements (volume controls + transfer number edit) when scaling. If you've fixed it manually through settings, you might need to reset it, e.g. deleting "dialpad" object from tSIP.json when tSIP is not running to recreate it with default values.
