### ISSUE TITLE
tSIP on MacOS?

### ISSUE THREAD

**Issue by neurocker** [tomek-o/tSIP#41]
Hi, thank you for your awesome program, especially for possibility to record different callers with stereo recording feature.
My question: is it possible to compile tSIP for MacOS? If yes, can you give some help info on how to do it?

**Comment by tomek-o** [comment]
I have no idea. FMX in newer C++ Builder might support MacOS, but there probably would be a lot of problems and I'm not able to test it.
Maybe starting with pure baresip or https://github.com/soramimi/qSIP would be easier.
