### ISSUE TITLE
User-Specific Settings

### ISSUE THREAD

**Issue by Ancient** [tomek-o/tSIP#43]
It would be awesome if there could be the possibility to have User-Specific Settings or at least Account Settings.
Currently i have PCs and/or RDSH Server where i would like to use tSip for multiple Users with their own settings.

For now, i have to copy the whole Application multiple times on the same machine to achieve this.
It would be great if there is chance to save Settings to the user Application Path or similar to have one installed App with one configuration per User.

**Comment by tomek-o** [comment]
There is /profiledir option, e.g. `tSIP.exe /profiledir="E:\zrzut\aa bb"` - specifying folder for audio files, scripts, JSON settings, basically everything but exe and dlls.

Would I use it myself though? Personally I feel like duplicating ~9 MB of binaries would be worth it given that it makes backups easier, probably gives better reliability, allows gradual, safer upgrading and maybe using different versions (even for same version number: with/without video) by different users.

**Comment by Ancient** [comment]
That's exactly what i needed. Works like a charm. Thanks!
