### ISSUE TITLE
tSIP on linux

### ISSUE THREAD

**Issue by mesb1** [tomek-o/tSIP#44]
Hi.

Not long time ago I have moved part of my home computers into mageia and fedora distros. And most of my daily used software is already there as a cross platform one.

But I would like to know if it is possible to get tsip working under Linux.
Have you tried to compile and run it?

**Comment by tomek-o** [comment]
I've only used tSIP under Wine.
Native Linux build would be very close to writing the GUI part from scratch and at this point https://github.com/soramimi/qSIP might be a better starting point.

**Comment by mesb1** [comment]
Hm, wine is also a solution.
Does all the functions works properly?

**Comment by tomek-o** [comment]
No, there are some problems.
Last time I've checked, Lubuntu 18 or maybe 20:
- there was no audio device selection available (Wine showing only default devices)
- TTS plugin was not working - audio was written by Wine to sound device instead to file
- plugins for USB HID were not working
Probably there is more.

**Comment by tomek-o** [comment]
Update: Wine is improving. With Lubuntu 24 LTS audio devices are enumerating correctly, so application sees multiple devices and using PulseAudio configuration is not required.

**Comment by mesb1** [comment]
Where you able to check if hid devices started working also?

Because my speakerphone device is visible by regular Linux as a sound device, but missing controls via buttons is quite annoying.

**Comment by tomek-o** [comment]
> Where you able to check if hid devices started working also?

They were still not visible not unfortunately.
