### ISSUE TITLE
Error when JSON patch button settings

### ISSUE THREAD

**Issue by mark05e** [tomek-o/tSIP#45]
I get an error when I try to update the buttons with [JSON patch](https://jsonpatch.com/). Any idea what I'm doing wrong here?

```json
[{ "op": "replace", "path": "/btnConf/25", "value": { "caption" : "Pound Sign", "number" : "#", "type" : 3 } }]
```
![image](https://github.com/tomek-o/tSIP/assets/1783193/bcffa722-7f84-492a-b774-e7caeb3ffce0)

```
---------------------------
tSIP
---------------------------
Access violation at address 006FFF14 in module 'tSIP.exe'. Read of address 00000000.
---------------------------
OK   
---------------------------
```

Running on:
tsip 0.03.03.00 (does not work on 0.03.01.00 as well)
Windows 10 22H2

**EDIT:**
Also tried something smaller - same error.

```json
[{ "op": "replace", "path": "/btnConf/25/caption", "value": "Pound Sign" }]
```

**Comment by tomek-o** [comment]
The name I've used might be misleading - it does not support JSON Patch, but rather creates sort of merge with previous configuration, keeping all settings that are not present in current configuration.
For your particular example "patch" might look like this (somehow ugly if one wants only to e.g. modify single button #100 or so):

`{
   "btnConf" : [
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {
         "caption" : "Pound Sign",
         "number" : "#",
         "type" : 3
      }
   ]
}
`
or in JSONedit:
![patch](https://github.com/tomek-o/tSIP/assets/43222462/8819802e-8db1-41a2-b2c1-cd84800ac9ba)

Regarding the crash: I'll fix this soon, this is not expected.

**Comment by mark05e** [comment]
>  For your particular example "patch" might look like this (somehow ugly if one wants only to e.g. modify single button #100 or so):
> ```{ "btnConf" : [ {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, { "caption" : "Pound Sign", "number" : "#", "type" : 3 } ] } ```

Thank you, this solution works. And you're right, it does seem like a lot for just updating a single button.


> Also note that there are separate "update" menu items for "main" and "buttons" settings.

Understood. I selected the wrong option when I took the screenshot.

**Comment by tomek-o** [comment]
I've added missing JSON checks in https://github.com/tomek-o/tSIP/commit/5b0e400dffab91897f77507cb0dab009f7b7f9a0 but I guess it can wait till the next release. Thank you for reporting.

**Comment by mark05e** [comment]
Thank you for your support! Will go ahead and close this ticket.
