### ISSUE TITLE
Phone number display(parked call)

### ISSUE THREAD

**Issue by hillxrem** [tomek-o/tSIP#49]
If a call from tSIP to Asterisk call park number(7XX) is made when some call is already parked in 7XX,
SIP messages seem to be exchanged in the following order
1. Request:INVITE from tsip
2. Status:200OK from Asterisk
3. Request:ACK from tSIP
4. Request:INVITE in-dialog from Asterisk
(In the case of Grandstream IP phones, 4. seems to be Request:Update)

This Request:INVITE in-dialog message has the phone number of parked call as P-Asserted-Identity, but even if “Use P-Asserted-Identity if present” is checked in the Display of tSIP's settings, call park number(7XX) appears on the display of tSIP.

I would like to see the phone number on tSIP display.  Is this a problem with asterisk or tSIP?

(72001:callpark 2002076:tsip 117:phone number)
![passerted](https://github.com/tomek-o/tSIP/assets/39339371/e2231bb9-1929-43da-8fa1-7c500c78a1ab)

**Comment by tomek-o** [comment]
It looks like I've broken re-INVITE event handling in version 0.3.
It should be fixed now in https://tomeko.net/tmp3/tSIP.exe
I haven't tried your exact message sequence, let me know if this works and thank you for reporting.

**Comment by hillxrem** [comment]
Thank you so much for your swift fix again. It worked perfectly. 
I hope this can also be included in the upcoming updates.

**Comment by tomek-o** [comment]
There was a very recent issue with LINE buttons initialization, executable at the link above is updated now and it looks like PAI display works now.

**Comment by hillxrem** [comment]
Thank you for fixing LINE button issue. However, there still seems to be a minor issue that call park number, not PAI, appears on LINE button just after a call park is taken, and the PAI appears after the call is switched (after it goes into HOLD state).
![linebutton](https://github.com/tomek-o/tSIP/assets/39339371/36d784d2-db68-4ab0-b205-fd0712a94792)

**Comment by tomek-o** [comment]
> there still seems to be a minor issue that call park number, not PAI, appears on LINE button just after a call park is taken, and the PAI appears after the call is switched (after it goes into HOLD state)

https://tomeko.net/tmp/tSIP.exe should fix this - button update after re-INVITE was missing.

**Comment by hillxrem** [comment]
This time, completely fixed. Much appreciated for fixing and side note!
