### ISSUE TITLE
Single instance parameter not working.

### ISSUE THREAD

**Issue by barsrb** [tomek-o/tSIP#5]
At first - thank you for this greate software!

We have problem with software. In settings "Single instance" checked. In tSIP.json parameter "SingleInstance" : true, but when application minimized or in tray, run exe create new procces and open yet one instance of allication.
Try to call tSip.exe with parameter /SHOWWINDOW,  /tsip="SHOWWINDOW" - nothing.
Is this bug or maybe we doing something wrong?

**Comment by tomek-o** [comment]
Thank you for the feedback.

Looks like second instance cannot find first one. It uses FindWindow() with class name ("TfrmMain") and window caption and it looks like I've missed that window caption is customizable in newer versions. I'm hoping this is the source of the problem and thus https://github.com/tomek-o/tSIP/commit/7b31d7a0ebdf9d7157075dd65b1e4ff94fa588fc would fix it.
Updated  binary is currently at http://tomeko.net/tmp/tSIP.exe - let me know if it fixes it in your case or is it different issue.
It affects both "Single instance" and click-to-call / command line parameter passing to previous instance.
For reference, command line is described at https://tomeko.net/software/SIPclient/browser_integration.php - syntax would be tSIP.exe /tsip=SHOWWINDOW

**Comment by barsrb** [comment]
Yes, caption was customized.
Update exe-file. Now it works!
Thank you!
