### ISSUE TITLE
LUA SCRIPT TO TRANSFER CALL

### ISSUE THREAD

**Issue by deccosantos** [tomek-o/tSIP#6]
Hi, this software is awesome.
I would like to know how to transfer call to specific number?

Thanks

**Comment by tomek-o** [comment]
This would be either
`BlindTransfer("123")`
or something like
`SendDtmf("*2")` (for attended transfer, using PABX feature code, perhaps followed by Sleep(500) and Hangup()).

Short list of custom functions is at [https://tomeko.net/software/SIPclient/script.php](https://tomeko.net/software/SIPclient/script.php) (few latest additions might be missing from time to time) and custom functions are implemented in [https://github.com/tomek-o/tSIP/blob/master/tSIP/scripting/ScriptExec.cpp](ScriptExec.cpp).
For more practical example: [https://tomeko.net/software/SIPclient/howto/originate.php](https://tomeko.net/software/SIPclient/howto/originate.php).

**Comment by tomek-o** [comment]
This is something close: [https://tomeko.net/software/SIPclient/howto/local_dtmfs.php](https://tomeko.net/software/SIPclient/howto/local_dtmfs.php), although I'm not sure if "on dial" event and current function set would be sufficient for you. In particular there is no method to override default action (i.e. sending DTMF) at the moment - I may need more precise description of your application.
To run similar script only when there is connected call, add at the start:
> call_state = GetCallState()
> if call_state ~= 6 then
>     return
> end

**Comment by deccosantos** [comment]
Hi, thanks for reply, but maybe you didn't understand my question. I am talking about numeric events received when caller clicks in specific mobile keyboard number. For example, a recorded voice says: If you want to talk with attendant, press 1, about finances, press 2, etc. Is there a way to catch this pressed number? I realized that in log it catch this:
“received event: '1' (end=0)” when caller clicks number 1;
“received event: '1' (end=1)" when finishes click

**Comment by tomek-o** [comment]
> “received event: '1' (end=0)”

So, DTMFs received by softphone? See [https://tomeko.net/software/SIPclient/howto/get_rx_dtmf.php](https://tomeko.net/software/SIPclient/howto/get_rx_dtmf.php).
For IVR applications there is note that audio announcements need timing and/or second or two of silence at the end, although in later version "on audio device error" script event and "Calls"/"Disconnect call on audio error" setting (to be unchecked) were added to allow end of audio file detection. To pass information/event from one script context (end of audio file) to another (call connected handling) SetVariable/GetVariable functions can be used.
