### ISSUE TITLE
Cannot dial numbers or connect to other accounts

### ISSUE THREAD

**Issue by elchvieh** [tomek-o/tSIP#8]
Using version 0.01.70.00, I can't seem to dial any number, external or internal. It always times out. (Note: I have not tested any previous versions)
I've set up the account data correctly, as it registers and I can see other accounts BLF info in the speed dial.
The log says
```
connecting to 'sip:dialednumber@provider;transport=tcp'..
sip:dialednumber@provider: session closed: Connection timed out
```
I've tried multiple other softphones which work fine, so I assume it's not the providers fault.

I've asked my provider if my server settings are correct and they said I am not supposed to call an account like this but only numbers like `35` (an internal phone extension) or `07654321` (0 is our "dial out" prefix for external numbers). But the `@provider` always gets attached to the number, but `35@provider` is not a valid account.

I am trying to replace some hardware phones with this and they only dial numbers, not accounts.
There are also some special numbers like `*9` to transfer any ringing account to me, but it then also gets dialed as `*9@provider`

Is dialing numbers only somehow possible without having the `@provider` attached?

**Comment by tomek-o** [comment]
SIP address always look like this - even with desk phones. This is just common convention that entering just a number is enough and device (or software) is creating full SIP address (also known as URI) from it by adding "sip:" and server address/name with optional port. Entering full URI would be just not practical with typical desktop phones. When receiving calls typically "server" part of the URI is stripped, only only user part (number) of URI is presented. It is also possible to dial using full URI - in phones manual this might be described as "direct IP calling", with tSIP I'm assuming that anything anything entered by user that starts with "sip:" would be full URI and nothing has to be added.

"Connection timed out" means that either provider is not receiving INVITE request from softphone or softphone is not receiving replies from provider. In the log window there is "Log received and transmitted SIP messages" showing what goes out/in. It would probably show only repeated INVITE messages from softphone, but attaching longer log might provide additional information.

In the line you quoted TCP transport is selected. Is this required by provider? If not, then I would definitely use UDP - more popular, better tested.

Are you sure softphone is registered and BLF(s) are presenting status of other extension(s)? This would be weird, typically it should be all or nothing. Most common issue is binding to wrong network interface. There is network interface selection in Settings/Network. If you have more than one physical interface and/or VirtualBox, VPN or similar software installed then select the one with access to the Internet. This kind of problem might be also detected by Help/Troubleshooting function (VirtualBox network interface seems to always have highest priority on Windows).

Let me know if switching to UDP and/or selecting network interface changes anything.

**Comment by elchvieh** [comment]
> There is network interface selection in Settings/Network. If you have more than one physical interface and/or VirtualBox, VPN or similar software installed then select the one with access to the Internet.

I do indeed have a virtualbox network interface, selecting the actual network interface made everything work!

>Are you sure softphone is registered and BLF(s) are presenting status of other extension(s)?

Oddly enough it just worked out of the box. Icons turn yellow when a line rings or red if it's busy.

>In the line you quoted TCP transport is selected.

I think our firewall blocks UDP requests on that port, I can't get the account registered when UDP is selected.

Everything is working now, thank you.
